#!/bin/bash

plain='\033[0m'

red='\e[31m'
yellow='\e[33m'
gray='\e[90m'
green='\e[92m'
blue='\e[94m'
magenta='\e[95m'
cyan='\e[96m'
none='\e[0m'
# Font Size
# h6 = SMALL , h4 = AVERAGE , h3 = LARGE
# Check Root
[[ $EUID -ne 0 ]] && echo -e "${red}Error: ${plain} You must use root user to run this script!\n" && exit 1

sed -i 's/#\?AllowTcpForwarding .*/AllowTcpForwarding yes/' /etc/ssh/sshd_config && sed -i 's/#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config && sed -i 's/#\?Banner .*/Banner \/etc\/ssh\/gcp_404/' /etc/ssh/sshd_config && /etc/init.d/ssh restart;
echo "
<h3><font color='red'>Mytel GCP SSH Public Key
</font></h3>
<h3><font color='red'>◈────⪧  Y.Y.P SSH Servers ⪦────◈


</font></h3>" | tee /etc/ssh/gcp_404 >/dev/null
useradd "ypp26" --shell=/bin/false -M
echo "ypp26:ypp26" | chpasswd

echo ""
IP=$(wget -qO- ipv4.icanhazip.com)

echo -e "\033[1;32m             ◈─ᗚ Host / IP   • ๛  \033[1;31m$IP"
echo -e "\033[1;32m             ◈─ᗚ Port        • ๛  6000"
echo -e "\033[1;32m             ◈─ᗚ Username    • ๛  yyp26"
echo -e "\033[1;32m             ◈─ᗚ Password    • ๛  yyp26"

echo -e "${red}[-] ═────────────────────────────⪧◇⪦───────────────────────────═ [-]    ${plain}"
echo -e "${green}                                                                       ${plain}"
echo -e "${yellow}                      I want time to stop                             ${plain}"
echo -e "${green}                                                                       ${plain}"
echo -e "${blue}             Because I always want to be by your side                    ${plain}"
echo -e "${green}                                                                       ${plain}"
echo -e "${green}            ──────────⪧═───────◇───────═⪦──────────                   ${plain}"
echo -e "${green}                                                                       ${plain}"
echo -e "${cyan}                     S . S . H  A C C O U N T                           ${plain}"
echo -e "${green}                                                                       ${plain}"
echo -e "${green}    ࿂ ═───────⪧.  Now the thing is ready to use.  ⪦───────═  ࿂        ${plain}"
echo -e "${green}                                                                       ${plain}"
echo -e "${red}[-] ═────────────────────────────⪧◇⪦───────────────────────────═ [-]    ${plain}"
echo -e "${red}                                                                         ${plain}"
echo -e "${red}            [-]──⪧  Y Y P   S S H   S e r v r r  ⪦──[-]                 ${plain}"
